markdown: rdiscount
permalink: /:year/:month/:title/
url: http://xwlogic.github.io
name: BH3NVN的个人站点
author: xwlogic
email1: xwlogic@gmail.com
email2: bh3nvn36@gmail.com
duoshuo: xwlogic
disqus: 
cnzz: 1000238058
github:
weibo: 
pygments: true
paginate: 18
